ALTER TABLE suppliers
ADD COLUMN fantasy_name VARCHAR(100),
ADD COLUMN giro VARCHAR(100),
ADD COLUMN website VARCHAR(150),
ADD COLUMN city VARCHAR(100),
ADD COLUMN discount_percentage DECIMAL(5,2),
ADD COLUMN currency VARCHAR(10),
ADD COLUMN bank_account VARCHAR(50),
ADD COLUMN bank_name VARCHAR(100),
ADD COLUMN category VARCHAR(50),
ADD COLUMN delivery_type VARCHAR(50),
ADD COLUMN avg_delivery_days INT,
ADD COLUMN payment_terms INT,
ADD COLUMN notes TEXT;
