ALTER TABLE sales ALTER COLUMN cliente_rut TYPE VARCHAR(20);
ALTER TABLE sales ALTER COLUMN cliente_razon_social TYPE VARCHAR(255);
ALTER TABLE sales ALTER COLUMN cliente_giro TYPE VARCHAR(255);
ALTER TABLE sales ALTER COLUMN cliente_direccion TYPE VARCHAR(255);
ALTER TABLE sales ALTER COLUMN cliente_email TYPE VARCHAR(255);
