-- =====================================================
-- V6: Fix demo user passwords
-- BCrypt hash for password: demo1234
-- Hash verified by registering test@test.cl via API
-- =====================================================

-- Update all demo users with correct BCrypt hash for "demo1234"
-- This hash was generated by Spring's BCryptPasswordEncoder
UPDATE users 
SET password_hash = '$2a$10$5ljXdm1W4iDg/DTzKa35x.jbDFx/S7rWsTiDOqLsciitlq1vi8Ska'
WHERE email IN (
    'admin@eltrigal.cl',
    'supervisor@eltrigal.cl', 
    'cajero1@eltrigal.cl',
    'cajero2@eltrigal.cl',
    'bodega@eltrigal.cl',
    'admin@donpedro.cl',
    'supervisor@donpedro.cl',
    'cajero1@donpedro.cl',
    'cajero2@donpedro.cl'
);

